import pyautogui
import time
video = input("ti thes na deis ")
time.sleep(0.5)
pyautogui.moveTo(1100,1055)
pyautogui.click()
time.sleep(2)
pyautogui.moveTo(504,77)
pyautogui.click()
pyautogui.write("https://www.youtube.com")
pyautogui.click()
pyautogui.press("enter")
time.sleep(2)
pyautogui.moveTo(700,160)
pyautogui.click()
pyautogui.write(video)
pyautogui.press("enter")
time.sleep(1)
pyautogui.moveTo(500,500)
pyautogui.click()
